### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by chriscatuk** [tdenolle/bayrol-poolaccess-mqtt#11]
it's been working flawlessly for a few months. I'm so happy you made this plugin.

I now notice it says

```
Installed version v2.03 (240618-1133)
Latest version v2.10 (240812-0831)
```

And it comes from your own web server: https://www.denolle.fr/bayrol/update.json

Having had some issues with the Bayrol Salt, I would appreciate to be free to upgrade it without them always sending me to a professional 1 hour away from my home.   Did you find a way to get the latest firmwares continuously? 

I particularly appreciate your plugin because it shows me in graphs what I suspected.

My reading jumps suddenly for a few days and gets back slowly to previous value. your Plugins makes it even more obvious with the history available.  now when it happens, I disable the production or after a few days I will be off the charts, and indeed I see the graph proving me right. Next summer I am ready to ask them to address it.

**Comment by tdenolle** [comment]
Hi @chriscatuk, thanks for your feedback, I appreciate.
The only way I found to get latest firmwares is to parse https://www.bayrol.fr/support-technique/automatic-salt,https://www.bayrol.fr/support-technique/automatic-cl-ph pages and build the update.json file on top of it, no url provided by Bayrol so far.
Regards,

**Comment by chriscatuk** [comment]
thank you, I see we can download the latest firmware from that page you shared: https://www.bayrol.fr/support-technique/automatic-salt

I'll close the issue as it was not an issue
