### ISSUE TITLE
Add-on does not start

### ISSUE THREAD

**Issue by sebkr** [tdenolle/bayrol-poolaccess-mqtt#6]
I tried to install your add-on and i got the following error in the logs:
`KeyError: 'MQTT_USER'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/PoolAccessMqttBridge.py", line 236, in <module>
    main(c)
  File "/app/PoolAccessMqttBridge.py", line 208, in main
    brocker_client = MqttClient(config["MQTT_HOST"], config["MQTT_PORT"], config["MQTT_USER"], config["MQTT_PASSWORD"])
                                                                          ~~~~~~^^^^^^^^^^^^^`
I configured the add-on as described in your installation manual and used the default values for topic prefix ("homeassistant"), mqtt base topic ("homeassistant"), host ("localhost") and port (1833). User and password are empty. What am I missing? Many thanks in advance.

**Comment by tdenolle** [comment]
Hi @sebkr, it looks like add-on is crashing when MQTT User is not set, I'll fix it in the next coming release.

**Comment by tdenolle** [comment]
Let's update to 1.3.2 release and let me know if still failing.
